[package]
name = "futures-signals"
version = "0.3.3"
authors = ["Pauan <pcxunlimited@gmail.com>"]
description = "Zero cost FRP signals using the futures crate"
repository = "https://github.com/Pauan/rust-signals"
homepage = "https://github.com/Pauan/rust-signals"
readme = "README.md"
license = "MIT"
keywords = ["signal", "reactive", "frp", "futures"]
categories = ["asynchronous"]

[dependencies]
futures-core-preview = "0.3.0-alpha.13"
futures-channel-preview = "0.3.0-alpha.13"
futures-util-preview = "0.3.0-alpha.13"
discard = "1.0.3"
# TODO make this optional
serde = "1.0.27"

[dev-dependencies]
futures-preview = "0.3.0-alpha.13"
futures-executor-preview = "0.3.0-alpha.13"
pin-utils = "0.1.0-alpha.3"
